PImage loadedImage;
 int brushSize;
 int brushColorR,brushColorG,brushColorB;
 int maxBrushSize;
 int[] lineCoordinates=new int[4];
 int lineStatus = 0;
 int[] triangleCoordinates=new int[6];
 int triangleStatus = 0;
  int[] rectCoordinates=new int[8];
 int rectStatus = 0;
 int saveStatus = 0;
 int drawSaveDelay = 1000;
 int drawState = 0;
 int delCount = 0;
 int delLimit = 50;
 int previewRenderDelay = 2;
 int previewCount = 0;
 int previewOpacity = 75;
 Tool[] hotbarTools = {new Hand(),new Pen(),new Line(),new Triangle(),new Rectangle(),new Circle(),new Pipette(),new Bucket()};
 Effect[] hotbarEffects = {new Poster(),new Invert(),new Blur(),new BlackAndWhite(),new Threshold()};
 int selectedTool = 0;
 int selectedEffect = 0;
 boolean filled = true;
Toolbar toolbar;
boolean enableOnClick = false;
boolean loadOnClick = false;
boolean clearOnClick = false;
boolean drawFocused = true;
